TimeTable.Web/Models/TimeTableViewModels/TimeTableViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using TimeTableDesigner.Shared.Entity.Database;

namespace TimeTableDesigner.Web.Models.TimeTableViewModels
{
    public class TimeTableViewModel
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime FirstDay { get; set; }
        public IEnumerable<Course> Courses { get; set; }

        public TimeTable ToTimeTable()
        {
            return null;
        }

        public static TimeTableViewModel Create(TimeTable timeTable)
        {
            return null;
        }
    }
}

TimeTable.Web/Controllers/TimeTableController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TimeTableDesigner.Shared.Access.Service;
using TimeTableDesigner.Shared.Entity.Domain;
using TimeTableDesigner.Web.Models;

namespace TimeTableDesigner.Web.Controllers
{
    [Authorize]
    public class TimeTableController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly IWebDataService _webDataService;
        private readonly ITimeTableService _timeTableService;

        public TimeTableController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager, 
            IWebDataService webDataService, 
            ITimeTableService timeTableService)
        {
            _webDataService = webDataService;
            _timeTableService = timeTableService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = User;
            var timeTables = await _timeTableService.ListTimeTablesForUserAsync(_userManager.GetUserId(User));
            return View();
        }
    }
}

TimeTable.Web/Views/TimeTable/CreateOrUpdate.cshtml
@model TimeTableDesigner.Web.Models.TimeTableViewModels.TimeTableViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2></h2>
<div id="calendar"></div>
<input type="button" id="a" value="asd" />
<input type="button" id="r" value="asd" />
@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function() {
            //$("#a").on("click",
            //    function() {
            //        $('#calendar').fullCalendar('renderEvent',
            //            {
            //                id: 'loller',
            //                title: 'asdasd',
            //                start: '2017-07-12T10:30:00',
            //                end: '2017-07-12T12:30:00'
            //            });
            //    });

            //$("#r").on("click",
            //    function() {
            //        $('#calendar').fullCalendar('removeEvents', 'loller');
            //    });

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                defaultView: 'agendaWeek',
                defaultDate: '@Model.FirstDay.ToString("yyyy-MM-dd")',
                locale: 'hu',
                navLinks: true,
                eventLimit: true
            });
        });
    </script>
}

TimeTable.Web/Views/TimeTable/Index.cshtml
@model IEnumerable<TimeTable>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Órarendek</h2>
<hr/>
@Html.ActionLink("Új órarend", "CreateOrUpdate", "TimeTable", null, new { @class = "btn-lg btn-primary" })
<hr/>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>Név</th>
            <th>Szemeszter</th>
            <th>Felvett kurzusok</th>
            <th></th>
        </tr>
        @foreach (var timeTable in Model)
        {
        <tr>
            <td>@timeTable.Name</td>
            <td>@timeTable.Semester</td>
            <td>@timeTable.Course.Count</td>
            <td>
                @Html.ActionLink("Megtekintés", "CreateOrUpdate", "TimeTable", new { id = timeTable.Id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Törlés", "Delete", "TimeTable", new { id = timeTable.Id }, new {@class = "btn btn-danger"})
            </td>
        </tr>
        }
    </table>
}
else
{
    <i>Nincsenek korábbi órarendek.</i>
}

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
}